<?php

declare(strict_types=1);

namespace ByteBuilders\T3ClickMark\Controller;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use ByteBuilders\T3ClickMark\Configuration\AccessControl;
use ByteBuilders\T3ClickMark\Service\AgencyDeskForwardingService;
use ByteBuilders\T3ClickMark\Service\PlatformFeatureService;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Http\JsonResponse;
use TYPO3\CMS\Core\Resource\ResourceFactory;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * eID controller that receives feedback submissions from the T3ClickMark widget.
 * Stores feedback locally in TYPO3 (database + FAL) and optionally forwards
 * to AgencyDesk API if configured.
 *
 * Authentication uses an HMAC token generated by InjectWidgetMiddleware,
 * since the BE_USER session is not available in eID context.
 */
class FeedbackApiController
{
    public function submitAction(ServerRequestInterface $request): ResponseInterface
    {
        $parsedBody = $request->getParsedBody();
        $uploadedFiles = $request->getUploadedFiles();

        // Verify submission token (generated by InjectWidgetMiddleware)
        $token = $parsedBody['submissionToken'] ?? '';
        $backendUserId = (int)($parsedBody['backendUserId'] ?? 0);

        if (!$this->verifySubmissionToken($token, $backendUserId)) {
            return new JsonResponse(['error' => 'Not authenticated'], 403);
        }

        // Validate required fields
        $title = trim($parsedBody['title'] ?? '');
        if ($title === '') {
            return new JsonResponse(['error' => 'Title is required'], 400);
        }

        // Video capture is a paid platform feature. Reject early — before any
        // record or file is stored — with a clear error instead of letting the
        // platform bounce the forward later (never silently dropped).
        if (!empty($uploadedFiles['videoRecording'])
            && !GeneralUtility::makeInstance(PlatformFeatureService::class)->isPremiumUnlocked()
        ) {
            return new JsonResponse([
                'error' => 'feature_not_available',
                'message' => 'Video-Aufnahme ist ab dem Agency-Tarif verfügbar.',
            ], 402);
        }

        // Save screenshot to temp file BEFORE FAL consumes it.
        // We need the file for both local FAL storage and AgencyDesk forwarding.
        $screenshotTempPath = null;
        if (!empty($uploadedFiles['annotatedScreenshot'])) {
            $screenshotTempPath = GeneralUtility::tempnam('t3cm_fwd_') . '.jpg';
            $stream = $uploadedFiles['annotatedScreenshot']->getStream();
            $stream->rewind();
            file_put_contents($screenshotTempPath, $stream->getContents());
        }

        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('tx_t3clickmark_domain_model_feedback');

        // Build the feedback record
        $record = [
            'pid' => $this->getStoragePid(),
            'tstamp' => time(),
            'crdate' => time(),
            'title' => $title,
            'description' => trim($parsedBody['description'] ?? ''),
            'status' => 'open',
            'priority' => $parsedBody['priority'] ?? 'medium',
            'category' => $parsedBody['category'] ?? 'change_request',
            'page_uid' => (int)($parsedBody['pageId'] ?? 0),
            'content_uid' => (int)($parsedBody['contentElementUid'] ?? 0),
            'content_type' => $parsedBody['contentType'] ?? '',
            'page_url' => $parsedBody['pageUrl'] ?? '',
            'backend_edit_link' => $parsedBody['backendEditLink'] ?? '',
            'browser_info' => $this->formatBrowserInfo($parsedBody),
            'viewport' => $this->formatViewport($parsedBody['viewport'] ?? ''),
            'css_selector' => $parsedBody['cssSelector'] ?? '',
            'console_errors' => (int)($parsedBody['consoleErrors'] ?? 0),
            'console_warnings' => (int)($parsedBody['consoleWarnings'] ?? 0),
            'failed_requests' => (int)($parsedBody['failedRequests'] ?? 0),
            'backend_user' => $backendUserId,
            'backend_username' => $parsedBody['backendUsername'] ?? '',
            'annotated_screenshot' => 0,
            'attachments' => 0,
            'video_recording' => 0,
            'forward_status' => 'pending',
            'forward_attempts' => 0,
        ];

        $connection->insert('tx_t3clickmark_domain_model_feedback', $record);
        $feedbackUid = (int)$connection->lastInsertId();

        // Handle file upload (annotated screenshot) — stores in FAL
        if (!empty($uploadedFiles['annotatedScreenshot'])) {
            $this->storeScreenshot($feedbackUid, $uploadedFiles['annotatedScreenshot'], 'annotated_screenshot');
        }

        // Handle attachment uploads (images, PDFs — max 5 files, 5 MB each)
        $attachments = $uploadedFiles['attachments'] ?? [];
        $attachmentCount = 0;
        $attachmentTempPaths = [];
        foreach ($attachments as $attachment) {
            if ($attachmentCount >= 5) {
                break;
            }
            if ($attachment->getSize() <= 0 || $attachment->getSize() > 5 * 1024 * 1024) {
                continue;
            }
            // Validate file extension
            $clientFilename = $attachment->getClientFilename() ?? '';
            $ext = strtolower(pathinfo($clientFilename, PATHINFO_EXTENSION));
            if (!in_array($ext, ['png', 'jpg', 'jpeg', 'webp', 'gif', 'pdf'], true)) {
                continue;
            }
            // Save temp copy for AgencyDesk forwarding before FAL consumes the stream
            $tempPath = GeneralUtility::tempnam('t3cm_att_') . '.' . $ext;
            $stream = $attachment->getStream();
            $stream->rewind();
            file_put_contents($tempPath, $stream->getContents());
            $attachmentTempPaths[] = ['path' => $tempPath, 'name' => $clientFilename, 'ext' => $ext];

            $this->storeFile($feedbackUid, $attachment, 'attachments', $attachmentCount + 1);
            $attachmentCount++;
        }

        // Handle video recording upload (Pro feature — WebM, max 50 MB)
        $videoTempPath = null;
        if (!empty($uploadedFiles['videoRecording'])) {
            $videoFile = $uploadedFiles['videoRecording'];
            if ($videoFile->getSize() > 0 && $videoFile->getSize() <= 50 * 1024 * 1024) {
                $videoTempPath = GeneralUtility::tempnam('t3cm_vid_') . '.webm';
                $stream = $videoFile->getStream();
                $stream->rewind();
                file_put_contents($videoTempPath, $stream->getContents());
                $this->storeFile($feedbackUid, $videoFile, 'video_recording', 1);
            }
        }

        // Forward to AgencyDesk API if configured
        $forwardingService = GeneralUtility::makeInstance(AgencyDeskForwardingService::class);
        $agencyDeskResult = $forwardingService->forwardFromParsedBody($parsedBody, $screenshotTempPath, $attachmentTempPaths, $videoTempPath);

        // Track delivery state (outbox). null = AgencyDesk not configured → stays 'pending'.
        if ($agencyDeskResult !== null) {
            $now = time();
            if (!empty($agencyDeskResult['forwarded']) && isset($agencyDeskResult['response']['id'])) {
                $connection->update(
                    'tx_t3clickmark_domain_model_feedback',
                    [
                        'external_id' => (string)$agencyDeskResult['response']['id'],
                        'forward_status' => 'sent',
                        'forward_attempts' => 1,
                        'forward_last_attempt' => $now,
                    ],
                    ['uid' => $feedbackUid]
                );
            } else {
                // Delivery failed (e.g. platform down) — the scheduler/banner will retry.
                $error = (string)($agencyDeskResult['error'] ?? ('HTTP ' . ($agencyDeskResult['statusCode'] ?? '?')));
                $connection->update(
                    'tx_t3clickmark_domain_model_feedback',
                    [
                        'forward_status' => 'failed',
                        'forward_attempts' => 1,
                        'forward_last_error' => substr($error, 0, 2000),
                        'forward_last_attempt' => $now,
                    ],
                    ['uid' => $feedbackUid]
                );
            }
        }

        // Clean up temp files
        if ($screenshotTempPath !== null && file_exists($screenshotTempPath)) {
            unlink($screenshotTempPath);
        }
        foreach ($attachmentTempPaths as $att) {
            if (file_exists($att['path'])) {
                unlink($att['path']);
            }
        }
        if ($videoTempPath !== null && file_exists($videoTempPath)) {
            unlink($videoTempPath);
        }

        $response = [
            'success' => true,
            'feedbackId' => $feedbackUid,
            'message' => 'Feedback submitted successfully',
        ];

        if ($agencyDeskResult !== null) {
            $response['agencyDesk'] = $agencyDeskResult;
        }

        return new JsonResponse($response, 201);
    }

    /**
     * Verify the HMAC submission token.
     * Checks both today and yesterday to handle midnight boundary.
     * In public widget mode, backendUserId = 0 is accepted.
     */
    private function verifySubmissionToken(string $token, int $backendUserId): bool
    {
        if ($token === '') {
            return false;
        }

        // In public mode (Pro feature), accept backendUserId = 0
        if ($backendUserId <= 0 && !AccessControl::isPublicWidgetEnabled()) {
            return false;
        }

        $encryptionKey = $GLOBALS['TYPO3_CONF_VARS']['SYS']['encryptionKey'] ?? '';

        // Check today's token
        $expectedToday = hash_hmac('sha256', $backendUserId . '|' . date('Y-m-d'), $encryptionKey);
        if (hash_equals($expectedToday, $token)) {
            return true;
        }

        // Also accept yesterday's token (handles midnight boundary)
        $expectedYesterday = hash_hmac('sha256', $backendUserId . '|' . date('Y-m-d', strtotime('-1 day')), $encryptionKey);
        return hash_equals($expectedYesterday, $token);
    }

    /**
     * Store an uploaded file via FAL and link it to the feedback record (generalized).
     */
    private function storeFile(int $feedbackUid, $uploadedFile, string $fieldName, int $sortingForeign = 1): void
    {
        $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
        $storage = $resourceFactory->getDefaultStorage();
        if ($storage === null) {
            return;
        }

        $targetFolderPath = 'user_upload/t3clickmark/';
        if (!$storage->hasFolder($targetFolderPath)) {
            $storage->createFolder('t3clickmark', $storage->getFolder('user_upload'));
        }
        $targetFolder = $storage->getFolder($targetFolderPath);

        $clientFilename = $uploadedFile->getClientFilename() ?? 'upload.bin';
        $ext = strtolower(pathinfo($clientFilename, PATHINFO_EXTENSION)) ?: 'bin';
        $filename = sprintf('feedback_%d_%s_%s.%s', $feedbackUid, $fieldName, uniqid(), $ext);

        $tempFile = GeneralUtility::tempnam('t3cm_') . '.' . $ext;
        $uploadedFile->moveTo($tempFile);

        if (!file_exists($tempFile) || filesize($tempFile) === 0) {
            return;
        }

        $file = $storage->addFile($tempFile, $targetFolder, $filename);

        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('sys_file_reference');

        $connection->insert('sys_file_reference', [
            'pid' => $this->getStoragePid(),
            'tstamp' => time(),
            'crdate' => time(),
            'uid_local' => $file->getUid(),
            'uid_foreign' => $feedbackUid,
            'tablenames' => 'tx_t3clickmark_domain_model_feedback',
            'fieldname' => $fieldName,
            'sorting_foreign' => $sortingForeign,
        ]);

        // Update the file count on the feedback record
        $feedbackConnection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('tx_t3clickmark_domain_model_feedback');

        // Count total references for this field
        $countQb = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getQueryBuilderForTable('sys_file_reference');
        $count = (int)$countQb->count('uid')
            ->from('sys_file_reference')
            ->where(
                $countQb->expr()->eq('uid_foreign', $countQb->createNamedParameter($feedbackUid, \Doctrine\DBAL\ParameterType::INTEGER)),
                $countQb->expr()->eq('tablenames', $countQb->createNamedParameter('tx_t3clickmark_domain_model_feedback')),
                $countQb->expr()->eq('fieldname', $countQb->createNamedParameter($fieldName))
            )
            ->executeQuery()
            ->fetchOne();

        $feedbackConnection->update(
            'tx_t3clickmark_domain_model_feedback',
            [$fieldName => $count],
            ['uid' => $feedbackUid]
        );
    }

    /**
     * Store an uploaded screenshot file via FAL and link it to the feedback record.
     */
    private function storeScreenshot(int $feedbackUid, $uploadedFile, string $fieldName): void
    {
        $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
        $storage = $resourceFactory->getDefaultStorage();
        if ($storage === null) {
            throw new \RuntimeException('No default FAL storage configured');
        }

        // Create target folder if it doesn't exist
        $targetFolderPath = 'user_upload/t3clickmark/';
        if (!$storage->hasFolder($targetFolderPath)) {
            $storage->createFolder('t3clickmark', $storage->getFolder('user_upload'));
        }
        $targetFolder = $storage->getFolder($targetFolderPath);

        // Generate a unique filename
        $filename = sprintf('feedback_%d_%s_%s.jpg', $feedbackUid, $fieldName, uniqid());

        // Use PSR-7 moveTo() — the standard way to persist uploaded files.
        $tempFile = GeneralUtility::tempnam('t3cm_') . '.jpg';
        $uploadedFile->moveTo($tempFile);

        if (!file_exists($tempFile) || filesize($tempFile) === 0) {
            throw new \RuntimeException('Uploaded file is empty or move failed for ' . $fieldName);
        }

        $fileSize = filesize($tempFile);
        $file = $storage->addFile($tempFile, $targetFolder, $filename);

        // Create sys_file_reference linking the FAL file to the feedback record
        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('sys_file_reference');

        $connection->insert('sys_file_reference', [
            'pid' => $this->getStoragePid(),
            'tstamp' => time(),
            'crdate' => time(),
            'uid_local' => $file->getUid(),
            'uid_foreign' => $feedbackUid,
            'tablenames' => 'tx_t3clickmark_domain_model_feedback',
            'fieldname' => $fieldName,
            'sorting_foreign' => 1,
        ]);

        // Update the feedback record's file count so Extbase resolves the relation
        $feedbackConnection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('tx_t3clickmark_domain_model_feedback');
        $feedbackConnection->update(
            'tx_t3clickmark_domain_model_feedback',
            [$fieldName => 1],
            ['uid' => $feedbackUid]
        );
    }

    /**
     * Combine browser and OS into a single readable string.
     */
    private function formatBrowserInfo(array $parsedBody): string
    {
        $browser = trim($parsedBody['browser'] ?? '');
        $os = trim($parsedBody['os'] ?? '');

        if ($browser !== '' && $os !== '') {
            return $browser . ' on ' . $os;
        }

        return $browser ?: $os;
    }

    /**
     * Format viewport JSON into a readable "width × height" string.
     */
    private function formatViewport(string $viewport): string
    {
        if ($viewport === '') {
            return '';
        }

        $data = json_decode($viewport, true);
        if (is_array($data) && isset($data['width'], $data['height'])) {
            return $data['width'] . ' × ' . $data['height'];
        }

        return $viewport;
    }

    /**
     * Get the storage page ID for feedback records.
     * Defaults to 0 (root page) — can be made configurable later.
     */
    private function getStoragePid(): int
    {
        return 0;
    }
}
