<?php

declare(strict_types=1);

namespace ByteBuilders\T3ClickMark\Controller;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use TYPO3\CMS\Core\Configuration\ExtensionConfiguration;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Http\JsonResponse;
use TYPO3\CMS\Core\Http\RequestFactory;
use TYPO3\CMS\Core\Resource\ResourceFactory;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * eID controller that receives feedback submissions from the T3ClickMark widget.
 * Stores feedback locally in TYPO3 (database + FAL) and optionally forwards
 * to AgencyDesk API if configured.
 *
 * Authentication uses an HMAC token generated by InjectWidgetMiddleware,
 * since the BE_USER session is not available in eID context.
 */
class FeedbackApiController
{
    /**
     * AgencyDesk API base URL. Changed per release cycle.
     */
    private const API_ENDPOINT = 'https://clickmark.bytebuilders.de/api/v1';

    public function submitAction(ServerRequestInterface $request): ResponseInterface
    {
        $parsedBody = $request->getParsedBody();
        $uploadedFiles = $request->getUploadedFiles();

        // Verify submission token (generated by InjectWidgetMiddleware)
        $token = $parsedBody['submissionToken'] ?? '';
        $backendUserId = (int)($parsedBody['backendUserId'] ?? 0);

        if (!$this->verifySubmissionToken($token, $backendUserId)) {
            return new JsonResponse(['error' => 'Not authenticated'], 403);
        }

        // Validate required fields
        $title = trim($parsedBody['title'] ?? '');
        if ($title === '') {
            return new JsonResponse(['error' => 'Title is required'], 400);
        }

        // Save screenshot to temp file BEFORE FAL consumes it.
        // We need the file for both local FAL storage and AgencyDesk forwarding.
        $screenshotTempPath = null;
        if (!empty($uploadedFiles['annotatedScreenshot'])) {
            $screenshotTempPath = GeneralUtility::tempnam('t3cm_fwd_') . '.png';
            $stream = $uploadedFiles['annotatedScreenshot']->getStream();
            $stream->rewind();
            file_put_contents($screenshotTempPath, $stream->getContents());
        }

        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('tx_t3clickmark_domain_model_feedback');

        // Build the feedback record
        $record = [
            'pid' => $this->getStoragePid(),
            'tstamp' => time(),
            'crdate' => time(),
            'title' => $title,
            'description' => trim($parsedBody['description'] ?? ''),
            'status' => 'open',
            'priority' => $parsedBody['priority'] ?? 'medium',
            'category' => $parsedBody['category'] ?? 'change_request',
            'page_uid' => (int)($parsedBody['pageId'] ?? 0),
            'content_uid' => (int)($parsedBody['contentElementUid'] ?? 0),
            'content_type' => $parsedBody['contentType'] ?? '',
            'page_url' => $parsedBody['pageUrl'] ?? '',
            'backend_edit_link' => $parsedBody['backendEditLink'] ?? '',
            'browser_info' => $this->formatBrowserInfo($parsedBody),
            'viewport' => $this->formatViewport($parsedBody['viewport'] ?? ''),
            'css_selector' => $parsedBody['cssSelector'] ?? '',
            'console_errors' => (int)($parsedBody['consoleErrors'] ?? 0),
            'console_warnings' => (int)($parsedBody['consoleWarnings'] ?? 0),
            'failed_requests' => (int)($parsedBody['failedRequests'] ?? 0),
            'backend_user' => $backendUserId,
            'backend_username' => $parsedBody['backendUsername'] ?? '',
            'annotated_screenshot' => 0,
        ];

        $connection->insert('tx_t3clickmark_domain_model_feedback', $record);
        $feedbackUid = (int)$connection->lastInsertId();

        // Handle file upload (annotated screenshot) — stores in FAL
        if (!empty($uploadedFiles['annotatedScreenshot'])) {
            $this->storeScreenshot($feedbackUid, $uploadedFiles['annotatedScreenshot'], 'annotated_screenshot');
        }

        // Forward to AgencyDesk API if configured
        $agencyDeskResult = null;
        if ($screenshotTempPath !== null) {
            $agencyDeskResult = $this->forwardToAgencyDesk($parsedBody, $screenshotTempPath);
            // Clean up temp file
            if (file_exists($screenshotTempPath)) {
                unlink($screenshotTempPath);
            }
        } else {
            // No screenshot but still try forwarding
            $agencyDeskResult = $this->forwardToAgencyDesk($parsedBody, null);
        }

        $response = [
            'success' => true,
            'feedbackId' => $feedbackUid,
            'message' => 'Feedback submitted successfully',
        ];

        if ($agencyDeskResult !== null) {
            $response['agencyDesk'] = $agencyDeskResult;
        }

        return new JsonResponse($response, 201);
    }

    /**
     * Verify the HMAC submission token.
     * Checks both today and yesterday to handle midnight boundary.
     */
    private function verifySubmissionToken(string $token, int $backendUserId): bool
    {
        if ($token === '' || $backendUserId <= 0) {
            return false;
        }

        $encryptionKey = $GLOBALS['TYPO3_CONF_VARS']['SYS']['encryptionKey'] ?? '';

        // Check today's token
        $expectedToday = hash_hmac('sha256', $backendUserId . '|' . date('Y-m-d'), $encryptionKey);
        if (hash_equals($expectedToday, $token)) {
            return true;
        }

        // Also accept yesterday's token (handles midnight boundary)
        $expectedYesterday = hash_hmac('sha256', $backendUserId . '|' . date('Y-m-d', strtotime('-1 day')), $encryptionKey);
        return hash_equals($expectedYesterday, $token);
    }

    /**
     * Store an uploaded screenshot file via FAL and link it to the feedback record.
     */
    private function storeScreenshot(int $feedbackUid, $uploadedFile, string $fieldName): void
    {
        $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
        $storage = $resourceFactory->getDefaultStorage();
        if ($storage === null) {
            throw new \RuntimeException('No default FAL storage configured');
        }

        // Create target folder if it doesn't exist
        $targetFolderPath = 'user_upload/t3clickmark/';
        if (!$storage->hasFolder($targetFolderPath)) {
            $storage->createFolder('t3clickmark', $storage->getFolder('user_upload'));
        }
        $targetFolder = $storage->getFolder($targetFolderPath);

        // Generate a unique filename
        $filename = sprintf('feedback_%d_%s_%s.png', $feedbackUid, $fieldName, uniqid());

        // Use PSR-7 moveTo() — the standard way to persist uploaded files.
        $tempFile = GeneralUtility::tempnam('t3cm_') . '.png';
        $uploadedFile->moveTo($tempFile);

        if (!file_exists($tempFile) || filesize($tempFile) === 0) {
            throw new \RuntimeException('Uploaded file is empty or move failed for ' . $fieldName);
        }

        $fileSize = filesize($tempFile);
        $file = $storage->addFile($tempFile, $targetFolder, $filename);

        // Create sys_file_reference linking the FAL file to the feedback record
        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('sys_file_reference');

        $connection->insert('sys_file_reference', [
            'pid' => $this->getStoragePid(),
            'tstamp' => time(),
            'crdate' => time(),
            'uid_local' => $file->getUid(),
            'uid_foreign' => $feedbackUid,
            'tablenames' => 'tx_t3clickmark_domain_model_feedback',
            'fieldname' => $fieldName,
            'sorting_foreign' => 1,
        ]);

        // Update the feedback record's file count so Extbase resolves the relation
        $feedbackConnection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('tx_t3clickmark_domain_model_feedback');
        $feedbackConnection->update(
            'tx_t3clickmark_domain_model_feedback',
            [$fieldName => 1],
            ['uid' => $feedbackUid]
        );
    }

    /**
     * Combine browser and OS into a single readable string.
     */
    private function formatBrowserInfo(array $parsedBody): string
    {
        $browser = trim($parsedBody['browser'] ?? '');
        $os = trim($parsedBody['os'] ?? '');

        if ($browser !== '' && $os !== '') {
            return $browser . ' on ' . $os;
        }

        return $browser ?: $os;
    }

    /**
     * Format viewport JSON into a readable "width × height" string.
     */
    private function formatViewport(string $viewport): string
    {
        if ($viewport === '') {
            return '';
        }

        $data = json_decode($viewport, true);
        if (is_array($data) && isset($data['width'], $data['height'])) {
            return $data['width'] . ' × ' . $data['height'];
        }

        return $viewport;
    }

    /**
     * Forward the feedback to AgencyDesk API (server-to-server).
     * Returns null if not configured, or an array with the forwarding result.
     */
    private function forwardToAgencyDesk(array $parsedBody, ?string $screenshotPath): ?array
    {
        try {
            $extConf = GeneralUtility::makeInstance(ExtensionConfiguration::class);
            $apiKey = trim((string)$extConf->get('t3clickmark', 'apiKey'));
        } catch (\Exception $e) {
            return null;
        }

        if ($apiKey === '') {
            return null;
        }

        $apiEndpoint = self::API_ENDPOINT;

        // Build multipart form data for the AgencyDesk API
        $boundary = 'T3ClickMark' . uniqid();
        $body = '';

        // All text fields the AgencyDesk API expects
        $fields = [
            'title' => $parsedBody['title'] ?? '',
            'description' => $parsedBody['description'] ?? '',
            'priority' => $parsedBody['priority'] ?? 'medium',
            'category' => $parsedBody['category'] ?? 'change_request',
            'contentElementUid' => $parsedBody['contentElementUid'] ?? '',
            'pageId' => $parsedBody['pageId'] ?? '',
            'contentType' => $parsedBody['contentType'] ?? '',
            'backendEditLink' => $parsedBody['backendEditLink'] ?? '',
            'pageUrl' => $parsedBody['pageUrl'] ?? '',
            'browser' => $parsedBody['browser'] ?? '',
            'os' => $parsedBody['os'] ?? '',
            'viewport' => $parsedBody['viewport'] ?? '',
            'cssSelector' => $parsedBody['cssSelector'] ?? '',
            'consoleErrors' => (string)($parsedBody['consoleErrors'] ?? '0'),
            'consoleWarnings' => (string)($parsedBody['consoleWarnings'] ?? '0'),
            'failedRequests' => (string)($parsedBody['failedRequests'] ?? '0'),
            'backendUsername' => $parsedBody['backendUsername'] ?? '',
            'backendUserId' => (string)($parsedBody['backendUserId'] ?? '0'),
        ];

        foreach ($fields as $name => $value) {
            $body .= '--' . $boundary . "\r\n";
            $body .= 'Content-Disposition: form-data; name="' . $name . '"' . "\r\n\r\n";
            $body .= $value . "\r\n";
        }

        // Attach screenshot file if available
        if ($screenshotPath !== null && file_exists($screenshotPath)) {
            $fileContent = file_get_contents($screenshotPath);
            $body .= '--' . $boundary . "\r\n";
            $body .= 'Content-Disposition: form-data; name="annotatedScreenshot"; filename="annotated.png"' . "\r\n";
            $body .= 'Content-Type: image/png' . "\r\n\r\n";
            $body .= $fileContent . "\r\n";
        }

        $body .= '--' . $boundary . "--\r\n";

        try {
            $requestFactory = GeneralUtility::makeInstance(RequestFactory::class);
            $response = $requestFactory->request(
                rtrim($apiEndpoint, '/') . '/feedback',
                'POST',
                [
                    'headers' => [
                        'X-API-Key' => $apiKey,
                        'Content-Type' => 'multipart/form-data; boundary=' . $boundary,
                    ],
                    'body' => $body,
                ]
            );

            $statusCode = $response->getStatusCode();
            $responseBody = json_decode((string)$response->getBody(), true) ?? [];

            return [
                'forwarded' => $statusCode >= 200 && $statusCode < 300,
                'statusCode' => $statusCode,
                'response' => $responseBody,
            ];
        } catch (\Exception $e) {
            return [
                'forwarded' => false,
                'error' => $e->getMessage(),
            ];
        }
    }

    /**
     * Get the storage page ID for feedback records.
     * Defaults to 0 (root page) — can be made configurable later.
     */
    private function getStoragePid(): int
    {
        return 0;
    }
}
